name: Java Maven CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-package:
    name: Build, Test & Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Run Node.js tests
        run: npm test

      - name: Build with Maven
        run: mvn compile --batch-mode

      - name: Run Maven tests
        run: mvn test --batch-mode

      - name: Package the application
        run: mvn package --batch-mode

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifact
          path: target/*.jar

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build-test-package
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        run: echo "🚀 Deploying the project..."
